### ISSUE TITLE
树洞无法正常显示，出现垃圾内容

### ISSUE THREAD

**Issue by Faith-Uchiha** [w1ndman/PkuHoleExportTool#5]
导出的过程中发现树洞整体不可用了，充斥着一些乱七八糟的语句，而且export-cited.txt也都是0字节的文件，请问是什么原因？

**Comment by Faith-Uchiha** [comment]
![image](https://github.com/w1ndman/PkuHoleExportTool/assets/26248309/3706a145-2084-4364-a7db-26ff7010787f)

**Comment by Toseic** [comment]
感谢您的issue！
这是因为短时间（一天至半天）内访问树洞次数过多导致账号被限制，理论上等一两天就会正常，
后续会想办法优化脚本使导出内容可以分几天导出以避免一天内导出过多

**Comment by w1ndman** [comment]
感谢您提出的issue！
这是因为短时间内访问次数过多导致账号被限制，理论上等一两天就会变正常。
后续可能会想办法让导出过程可以分多天导出以避免这种情况。

**Comment by Faith-Uchiha** [comment]
> 感谢您提出的issue！ 这是因为短时间内访问次数过多导致账号被限制，理论上等一两天就会变正常。 后续可能会想办法让导出过程可以分多天导出以避免这种情况。

好的，7.10零点的时候已经可以刷出内容了。由于是毕业生，最后的时光刷不出内容还是有点焦躁的，昨天以为从此不能用了。

感谢您分享的脚本！

**Comment by w1ndman** [comment]
> > 感谢您提出的issue！ 这是因为短时间内访问次数过多导致账号被限制，理论上等一两天就会变正常。 后续可能会想办法让导出过程可以分多天导出以避免这种情况。
> 
> 好的，7.10零点的时候已经可以刷出内容了。由于是毕业生，最后的时光刷不出内容还是有点焦躁的，昨天以为从此不能用了。
> 
> 感谢您分享的脚本！

谢谢！毕业愉快！
